### ISSUE TITLE
my quest controller not recognized

### ISSUE THREAD

**Issue by chanhoon** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#14]
i set all things. but in steam vr home. i cant see my controller. i changed vive to cv1. my driver is latest version. what should i do?
![image](https://user-images.githubusercontent.com/53574882/62308011-a1558380-b4bf-11e9-86a6-bf30e2b1cfb9.png)

**Comment by GennadiyAMD** [comment]
@chanhoon - Please attach a copy of your settings.json and c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log.

**Comment by chanhoon** [comment]
Here you go thanks
setting.json 
{
	"Application" : 
	{
		"AdjustChaperone" : true,
		"EnableManagementServer" : false,
		"HeadsetProfile" : "Oculus Rift CV1",
		"ManagementServerPort" : 8080,
		"PairedHeadsetsOnly" : false,
		"PairingModeEnabled" : false,
		"UseControllers" : false
	},
	"Audio" : 
	{
		"In_Channels" : 2,
		"In_SampleFormat" : "S16",
		"In_SampleRate" : 44100,
		"Out_AudioBitrate" : 128000,
		"Out_TimeShift" : 0
	},
	"Common" : 
	{
		"SettingsVersion" : 8
	},
	"Controller" : 
	{
		"DOF" : 6,
		"Description" : ""
	},
	"Display" : 
	{
		"DOF" : 6,
		"DumpPath" : "",
		"EnableDump" : false,
		"EncoderResolution" : 
		{
			"height" : 0,
			"width" : 0
		},
		"EyeResolution" : 
		{
			"height" : 1440,
			"width" : 1440
		},
		"FOV" : 
		{
			"height" : 1.7453292608261108,
			"width" : 1.7453292608261108
		},
		"IPD" : 0.0640000030398369,
		"MaxFrameRate" : 10000.0000000000000000,
		"MinFrameRate" : 40.0000000000000000,
		"VideoBitrate" : 100000000,
		"VideoCodec" : "default"
	},
	"Headset" : 
	{
		"DatagramSize" : 65507,
		"LogPath" : "",
		"Network" : "UDP",
		"Port" : 1235,
		"VirtualWallSize" : 
		{
			"height" : 0.0000000000000000,
			"width" : 0.0000000000000000
		},
		"VirtualWallType" : "None"
	}
}

---------------------------------------------------------------------------------------------------------------
AMDWirelessVR.log

2019-08-02 00:43:11.426     5B1C [VideoPipeline]    Info: Ellesmere GPU detected
2019-08-02 00:43:11.606     5B1C [AWVRServerImpl]    Info: StartService() Network services started. url=UDP://*:1235
2019-08-02 00:43:11.606     5B1C [NetworkServer]    Info: Server started, listening for incoming connections on UDP://*:1235
2019-08-02 00:43:11.611     5B1C [IServerTrackedDeviceProviderImpl]    Info: Init() - OpenVR setting set
2019-08-02 00:43:11.611     5B1C [IServerTrackedDeviceProviderImpl]    Info: CreateDeviceDriver(): Device '/hmd' initialized.
2019-08-02 00:43:11.611     5B1C [DisplayDriver]    Info: Display '/hmd' connected.
2019-08-02 00:43:11.612     5B1C [DeviceDriver]    Info: Activate(1), DeviceID=/hmd
2019-08-02 00:43:11.612     5B1C [DeviceDriver]    Info: Activate(1), DeviceID=/hmd, resource root set to C:/Program Files/AMD/WVR/OpenVR/bin/win64/../../resources
2019-08-02 00:43:11.615     5B1C [DeviceDriver]    Info: ReadCorrectionFromChaperoneSetup() id=10 found
2019-08-02 00:43:11.615     5B1C [DisplayDriver]    Info: DeviceID = /hmd
2019-08-02 00:43:11.616     5B1C [DeviceDriver]    Info: Activate(0), DeviceID=/hmd
2019-08-02 00:43:11.616     5B1C [DeviceDriver]    Info: Activate(0), DeviceID=/hmd, resource root set to C:/Program Files/AMD/WVR/OpenVR/bin/win64/../../resources
2019-08-02 00:43:11.617     5B1C [DeviceDriver]    Info: ReadCorrectionFromChaperoneSetup() id=10 found
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: DeviceID = /hmd
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetWindowBounds(0, 0, 2880, 1440)
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: IsDisplayOnDesktop() = false
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: IsDisplayRealDisplay() = false
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetRecommendedRenderTargetSize(1440, 1440)
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetProjectionRaw(0, -1.191754, 1.191754, -1.191754, 1.191754)
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetEyeOutputViewport(0, 0, 0, 1440, 1440)
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetProjectionRaw(1, -1.191754, 1.191754, -1.191754, 1.191754)
2019-08-02 00:43:11.617     5B1C [DisplayDriver]    Info: GetEyeOutputViewport(1, 1440, 0, 1440, 1440)
2019-08-02 00:43:11.624     58FC [Comm::Server]    Info: Starting server...
2019-08-02 00:43:15.064     5E10 [DisplayDriver]    Info: CreateSwapTextureSet() succeded process=24172 size=1440x1440 format=29 sampleCount=1 id=1
2019-08-02 00:43:15.065     5E10 [DisplayDriver]    Info: CreateSwapTextureSet() succeded process=24172 size=1440x1440 format=29 sampleCount=1 id=2
2019-08-02 00:43:16.954     5B1C [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=21384
2019-08-02 00:43:24.000     2BC0 [DisplayDriver]    Info: CreateSwapTextureSet() succeded process=23800 size=2345x2345 format=29 sampleCount=1 id=3
2019-08-02 00:43:24.023     2BC0 [DisplayDriver]    Info: CreateSwapTextureSet() succeded process=23800 size=2345x2345 format=29 sampleCount=1 id=4
2019-08-02 00:44:28.077     58FC [AWVRServerImpl]    Info: UDPServer::OnCreateSession: Discovery session created
2019-08-02 00:44:28.077     58FC [Comm::DatagramServer]    Info: New session created
2019-08-02 00:44:28.077     58FC [WVRServerSession]    Info: HelloRequest command received from 192.168.0.17:34434
2019-08-02 00:44:28.556     58FC [AWVRServerImpl]    Info: UDPServer::OnCreateSession: UDP session created
2019-08-02 00:44:28.556     58FC [NetworkServer]    Info: Client connection request received
2019-08-02 00:44:28.556     58FC [NetworkServer]    Info: Client connection request accepted
2019-08-02 00:44:28.556     58FC [Comm::DatagramServer]    Info: New session created
2019-08-02 00:44:28.556     58FC [IServerTrackedDeviceProviderImpl]    Info: CreateDeviceDriver(): Device '/hmd' already exists.
2019-08-02 00:44:28.556     58FC [DisplayDriver]    Info: Display '/hmd' connected.
2019-08-02 00:44:28.556     58FC [VideoPipeline]    Info: Initialize(): Display: AMD WVR GearVR
Codec: hevc
Render Resolution: 1440x1440
Encode Resolution: 1440x1440@71.8097fps
IPD: 0.064
Aspect: 1
Bitrate: 50000000 bps
Stereo: yes
SeparateEyeProcessing: yes
Received from HMD: yes

2019-08-02 00:44:28.557     58FC [VideoPipeline]    Info: InitializeConverter()
2019-08-02 00:44:28.575     58FC [VideoPipeline]    Info: InitializeEncoder() start
2019-08-02 00:44:28.590     58FC [VideoPipeline]    Info: InitializeEncoder(HEVC) succeeded
2019-08-02 00:44:28.591     58FC [NetworkServer]    Info: Sent video extra data
2019-08-02 00:44:28.591     58FC [NetworkServer]    Info: Sent StartSensor
2019-08-02 00:44:28.592     58FC [VideoPipeline]    Info: InitializeEncoder() start
2019-08-02 00:44:28.597     58FC [VideoPipeline]    Info: InitializeEncoder(HEVC) succeeded
2019-08-02 00:44:28.597     58FC [AMFAudioCaptureImpl]    Info: Terminate()
2019-08-02 00:44:28.597     58FC [AMFAudioCaptureImpl]    Info: Init()
2019-08-02 00:44:28.804     58FC [AudioPipeline]   Error: ..\..\..\..\..\..\runtime\src\awvr\wvr\AudioPipeline.cpp(103):AMF_ERROR 1 : AMF_FAIL: LoadExternalComponent(AudioConverterFFMPEG) failed
2019-08-02 00:44:28.804     58FC [NetworkServer]   Error: ..\..\..\..\..\..\runtime\src\awvr\wvr\HeadsetImpl.cpp(572):Failed to initialize audio pipeline
2019-08-02 00:44:28.804     58FC [NetworkServer]    Info: OnServiceStart - Success
2019-08-02 00:44:28.804     58FC [NetworkServer]    Info: OnServiceMessage - SERVICE_OP_CODE_START
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Controller: ID = /ctrlLeft
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/x
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/y
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/sys
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/tr
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/grip
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Input Control: = /ctrlLeft/in/js
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Output Control: = /ctrlLeft/out/haptic
2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: 

2019-08-02 00:44:28.804     58FC [ControllerImpl]    Info: Controller: ID = /ctrlRight
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Input Control: = /ctrlRight/in/a
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Input Control: = /ctrlRight/in/b
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Input Control: = /ctrlRight/in/tr
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Input Control: = /ctrlRight/in/grip
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Input Control: = /ctrlRight/in/js
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: Output Control: = /ctrlRight/out/haptic
2019-08-02 00:44:28.805     58FC [ControllerImpl]    Info: 

2019-08-02 00:44:28.998     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.005     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.213     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.221     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.431     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.438     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.648     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.654     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.868     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:29.876     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.094     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=330 newID=333
2019-08-02 00:44:30.094     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=335
2019-08-02 00:44:30.094     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=336
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=337
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=338
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=339
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=340
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=341
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=342
2019-08-02 00:44:30.095     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=343
2019-08-02 00:44:30.096     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=333 newID=344
2019-08-02 00:44:30.099     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.105     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.314     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.326     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.531     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:30.538     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:32.899     58FC [NetworkServer]    Info: Average latency: full 89.62(average 89.62) client 48.63 server 33.15 encoder 13.06 network  7.83 decoder 17.31, frame time 13.90 ms
2019-08-02 00:44:36.853     58FC [NetworkServer]    Info: Average latency: full 60.35(average 74.98) client 28.16 server 29.34 encoder 13.32 network  2.85 decoder 15.34, frame time 13.95 ms
2019-08-02 00:44:40.806     58FC [NetworkServer]    Info: Average latency: full 62.79(average 70.92) client 30.20 server 29.71 encoder 13.75 network  2.87 decoder 14.89, frame time 13.95 ms
2019-08-02 00:44:44.762     58FC [NetworkServer]    Info: Average latency: full 61.27(average 68.51) client 28.48 server 29.51 encoder 13.44 network  3.28 decoder 14.20, frame time 13.95 ms
2019-08-02 00:44:47.617     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=4253 newID=4267
2019-08-02 00:44:48.715     58FC [NetworkServer]    Info: Average latency: full 62.14(average 67.24) client 28.41 server 30.67 encoder 13.81 network  3.06 decoder 15.17, frame time 13.95 ms
2019-08-02 00:44:52.669     58FC [NetworkServer]    Info: Average latency: full 58.45(average 65.77) client 26.80 server 29.31 encoder 13.30 network  2.34 decoder 12.97, frame time 13.98 ms
2019-08-02 00:44:55.142     58FC [FlowCtrlProtocol]    Info: Message send from gap. oldID=5943 newID=5956
2019-08-02 00:44:55.479     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:55.479     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:55.765     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:55.766     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.001     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.001     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.272     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.273     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.517     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.517     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.790     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:56.790     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.013     58FC [NetworkServer]    Info: Average latency: full 72.25(average 66.70) client 34.43 server 32.25 encoder 14.24 network  5.58 decoder 14.53, frame time 13.97 ms
2019-08-02 00:44:57.021     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.021     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.298     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.299     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.550     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.550     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.810     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:57.816     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.130     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.136     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.444     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.451     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.763     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:58.771     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.079     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.084     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.399     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.406     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.714     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:44:59.721     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.033     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.041     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.354     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.363     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.664     58FC [NetworkServer]    Info: Average latency: full 85.21(average 69.01) client 45.72 server 31.32 encoder 11.82 network  8.17 decoder 11.89, frame time 13.95 ms
2019-08-02 00:45:00.669     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:00.676     58FC [NetworkServer]    Info: OnServiceMessage - VIDEO_OP_CODE_FORCE_IDR
2019-08-02 00:45:04.010     58FC [NetworkServer]    Info: StopStreaming() start
2019-08-02 00:45:04.010     58FC [IServerTrackedDeviceProviderImpl]   Error: ..\..\..\..\..\..\runtime\src\awvr\openvr\IServerTrackedDeviceProviderImpl.cpp(394):OnDeviceDisconnected(): Device '/ctrlLeft' is not connected.
2019-08-02 00:45:04.010     58FC [IServerTrackedDeviceProviderImpl]   Error: ..\..\..\..\..\..\runtime\src\awvr\openvr\IServerTrackedDeviceProviderImpl.cpp(394):OnDeviceDisconnected(): Device '/ctrlRight' is not connected.
2019-08-02 00:45:04.010     58FC [IServerTrackedDeviceProviderImpl]    Info: OnDeviceDisconnected(/hmd)
2019-08-02 00:45:04.010     58FC [DisplayDriver]    Info: Display '/hmd' disconnected.
2019-08-02 00:45:04.010     58FC [VideoPipeline]    Info: Terminate()...
2019-08-02 00:45:04.010     58FC [VideoPipeline]    Info: Waiting for the poller thread to stop...
2019-08-02 00:45:04.021     58FC [VideoPipeline]    Info: Shutting down encoder...
2019-08-02 00:45:04.027     58FC [VideoPipeline]    Info: Shutting down CSC...
2019-08-02 00:45:04.029     58FC [NetworkServer]    Info: Sent StopSensor
2019-08-02 00:45:04.029     58FC [NetworkServer]    Info: OnServiceStop: Client connection terminated, reason: stop command
2019-08-02 00:45:04.029     58FC [NetworkServer]    Info: OnServiceMessage - SERVICE_OP_CODE_STOP
2019-08-02 00:45:09.049     58FC [SessionManager]    Info: Session timed out
2019-08-02 00:45:09.049     58FC [WVRServerSession]    Info: AWVRDiscoveryServerSessionImpl destroyed
2019-08-02 00:45:09.049     58FC [WVRServerSession]    Info: AWVRUDPServerSessionImpl destroyed
2019-08-02 00:45:09.049     58FC [WVRServerSession]    Info: Session destroyed
2019-08-02 00:45:09.049     58FC [WVRServerSession]    Info: AWVRUDPServerSessionImpl destroyed
2019-08-02 00:45:09.049     58FC [WVRServerSession]    Info: Session destroyed
2019-08-02 00:51:33.249     2BC0 [DisplayDriver]    Info: DestroySwapTextureSet() succeded id=3
2019-08-02 00:51:33.249     2BC0 [DisplayDriver]    Info: DestroySwapTextureSet() succeded id=4
2019-08-02 00:51:33.249     2BC0 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=23800
2019-08-02 00:51:33.253      AE8 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=24232
2019-08-02 00:51:33.412     6074 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=23596
2019-08-02 00:51:33.457     6078 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=24316
2019-08-02 00:51:33.457     6080 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=21156
2019-08-02 00:51:33.457     609C [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=18852
2019-08-02 00:51:33.457     6088 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=21708
2019-08-02 00:51:33.457     60A0 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=23576
2019-08-02 00:51:34.079     260C [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=16612
2019-08-02 00:51:35.595     5CCC [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=23452
2019-08-02 00:51:35.748     5248 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=3524
2019-08-02 00:51:35.951     5E10 [DisplayDriver]    Info: DestroyAllSwapTextureSets() succeded process=24172
2019-08-02 00:51:36.043     5970 [DeviceDriver]    Info: TrackableDeviceDriver::Deactivate()
2019-08-02 00:51:36.043     5970 [DisplayDriver]    Info: Terminate() - Display driver terminated id=/hmd
2019-08-02 00:51:36.043     5970 [DeviceDriver]    Info: TrackableDeviceDriver::Deactivate()
2019-08-02 00:51:36.043     5970 [DisplayDriver]    Info: Terminate() - Display driver terminated id=/hmd

**Comment by GennadiyAMD** [comment]
@chanhoon - set the Use Third-Party Controller option on the ReLive page in Radeon Settings to Disabled (or change the UseControllers to true in the Application section in settings.json).

The Use Third-Party Controllers is meant for headsets with a 3DoF controller when using games that can use an XBox gamepad or other controllers. When you enable it, it turns off the controller driver in SteamVR so that the two controllers don't interfere with each other. For headsets like Quest it should be set to Disabled.

**Comment by GennadiyAMD** [comment]
@chanhoon - unrelated to controllers, you also have audio capture failing to initialize. This is probably because you also have another streaming solution registered at the same time and they get a hold of the audio pipeline first. Remove them from the external_drivers array in  %LOCALAPPDATA%\openvr\openvrpaths.vrpath and restart SteamVR and you should have your audio working as well.

**Comment by chanhoon** [comment]
wow it workes but why only left controller vibe work?

**Comment by GennadiyAMD** [comment]
@chanhoon - known issue, fixed in the upcoming Adrenalin 19.8.1 release. Make sure to get it once its out.

**Comment by chanhoon** [comment]
okay thanks

**Comment by RobbeSchepens** [comment]
Hi, has this issue been fixed? I'm looking into getting a new Navi GPU and an Oculus Quest, yet I'm trying to figure out which issues still remain. Please close issues once they are resolved and confirmed.

**Comment by GennadiyAMD** [comment]
Hi,

Yes, it's been resolved a while ago. The reason why we don't close them right away is because sometimes threads diverge or report multiple issues.

Navi and Quest should work very well together.


-------- Original Message --------
