### ISSUE TITLE
No microphone streaming on quest

### ISSUE THREAD

**Issue by RamesTheGeneric** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#23]
Whenever I use my Quest to stream games, it doesn't appear to be streaming the audio from the Quest's built in mic for microphone inputs.

**Comment by psychosomaticdragon** [comment]
Having the same issue - headset microphone enabled in steamVR, but nothing seems to come through.

**Comment by cmcosta81** [comment]
Have you found a solution? I haven't been able to get it working either was thinking virtual cable software might somehow handle it..

**Comment by GennadiyAMD** [comment]
@cmcosta81 - currently ReLive VR does not support streaming audio from the headset's microphone. For the time being I'd suggest to use a bluetooth headset with a microphone if you need mic input.

**Comment by YukihoAA** [comment]
Hi, @GennadiyAMD 

I Just Install ReLive VR today, and it looks very beautiful graphics on VRChat better than ALVR or Virtual Desktop.

I'm now using RX 590 and Oculus Quest but Oculus Link with AMD graphics was not good as i expected. (it seems RX590 is not enough to use Oculus Link)

but ReLive VR is super beautiful and very fast (and also stabilized) so if ReLive for VR has Mic supports, I can choose Radeon Graphics again because it has better efficiency than other Graphics. 
(ReLive VR is even better than Oculus Link with annoying USB cables!)

Also at this momment, ReLive VR streams output audio to Headset with PC speaker too, but I want to suggest to make audio separated like Oculus Quest do it originally.

I hope ReLive VR will support headset mic soon.

**Comment by philongrobo** [comment]
I have to buy a wireless microphone because there is no microphone support. Hope Relive will support soon.

**Comment by Dirro** [comment]
Is this still currently unsupported for latest update?

**Comment by GennadiyAMD** [comment]
@Dirro - still unsupported. This is a much bigger feature that involves a lot more. We're working on this, I know that you're eager to get this feature, but please give us some time :)

**Comment by TheGP** [comment]
@GennadiyAMD how many years do you need? Or waiting gpu prices go down so we can buy Nvidia?

**Comment by GennadiyAMD** [comment]
@philongrobo, @Dirro, @YukihoAA, @RamesTheGeneric, @psychosomaticdragon, @cmcosta81 -  please check out v2.0 beta, just posted it. Note that it's not on Sidequest though - dowload from here.

Any feedback is highly welcome. Thanks for your patience while waiting for it!

**Comment by tempestCognitor** [comment]
@GennadiyAMD Thanks for implementing this feature! I tried the new beta version with BigScreen VR, but the mic had quality issues. If I select the AMD streaming device as the mic in BigScreen, it was picking up my mic, but the frequency was off, I sounded very low and hard to understand to my friends in the room.

Device details: Oculus Quest (1)
Radeon Software Version: 21.9.2
PC details: AMD Radeon RX 6800XT, AMD Ryzen 7 5800X

Not sure if it helps, but I'll attach logs as well. I was playing around a bit with bitrate, and kept running into VIDEO_OP_CODE_FORCE_IDR messages, but I think that's probably unrelated.
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/7218427/AMDWirelessVR.log)

**Comment by GennadiyAMD** [comment]
@tempestCognitor - thanks for the feedback! FORCE_IDR are definitely unrelated to the microphone, that's part of the new quality of service algorithm we have implemented, which might also need a bit more tuning for older devices like Quest 1 where the decoder is not as fast. This would cause frame rate fluctuations, but has nothing to do with the microphone. You can reduce these fluctuations by increasing the minimum framerate - set the MinFrameRate in the Display section of settings.json to about 65.

I was able to reproduce the frequency problem with the microphone today, but very intermittently and it went away after rebooting the PC. We're looking into it, thanks a lot for reporting this!

**Comment by thedutchglaswegian** [comment]
I still not able to get microphone working after going through the Json file and changed the microphone value to true.
also checked in regi edit and changed the AMD values as well for audio as they were turned off, but no dice.
I'm running radeon version 22.1.1
everything else works fine, it is just the mic not being picked up. 

{
	"Application" : 
	{
		"AdjustChaperone" : true,
		"EnableManagementServer" : true,
		"HeadsetProfile" : "Oculus Quest 2",
		"ManagementServerPort" : 8080,
		"PairedHeadsetsOnly" : true,
		"PairingModeEnabled" : false,
		"UseControllers" : true
	},
	"Audio" : 
	{
		"In_CaptureSource" : false,
		"In_ChannelLayout" : 0,
		"In_Channels" : 2,
		"In_SampleFormat" : "S16",
		"In_SampleRate" : 48000,
		"In_StreamSampleRate" : 0,
		"Out_AudioBitrate" : 128000,
		"Out_TimeShift" : 0
	},
	"Common" : 
	{
		"SettingsVersion" : 10
	},
	"Controller" : 
	{
		"DOF" : 6,
		"Description" : null
	},
	"Display" : 
	{
		"10BitSRGB" : false,
		"DOF" : 6,
		"DumpPath" : null,
		"EnableDump" : false,
		"EncoderResolution" : 
		{
			"height" : 0,
			"width" : 0
		},
		"EncoderStereo" : true,
		"EyeResolution" : 
		{
			"height" : 1920,
			"width" : 2560
		},
		"FOV" : 
		{
			"height" : 1.7453292608261108,
			"width" : 1.7453292608261108
		},
		"IPD" : 0.0640000030398369,
		"KeepAspectRatio" : false,
		"MaxFrameRate" : 120.0000000000000000,
		"MinFrameRate" : 60.0000000000000000,
		"NonLinearScale" : true,
		"VideoBitrate" : 170000000,
		"VideoCodec" : "avc",
		"VideoEnableHDR" : true,
		"VideoSliceCount" : 1,
		"VideoSliceOutput" : false
	},
	"Headset" : 
	{
		"BindInterface" : "*",
		"DatagramSize" : 65507,
		"EnableNetwork" : true,
		"KeyboardPresent" : true,
		"LogPath" : "C:\Program Files (x86)\Steam\logs\",
		"MaxUserCount" : 1,
		"Microphone" : true,
		"MousePresent" : true,
		"Network" : "TCP",
		"Port" : 1235,
		"TouchScreenPresent" : false,
		"UserConnectionTimeout" : 30,
		"VerifyFirewall" : true
	}
}

**Comment by FnBrian79** [comment]
I think the drivers are missing for the windows app, but my might seem to be working fine. It just has a red X that's too within the app, which is.
